
export enum UserStatus {
	PENDING_VERIFICATION = "PENDING_VERIFICATION",
	ACTIVE = "ACTIVE",
	SUSPENDED = "SUSPENDED",
	BLOCKED = "BLOCKED",
	BANNED = "BANNED",
	DEACTIVATED = "DEACTIVATED",
	CLOSED = "CLOSED",
	DORMANT = "DORMANT",
}
